name: XCP_lite Default

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    tags: ["**"]

concurrency:
  group: ${{ (github.ref == 'refs/heads/main') && 'main' || format('{0}-{1}', github.workflow, github.ref) }} # concurrency does not include main branch
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: [production]
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
    - name: Run linter
      run: cargo clippy
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [production]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Build binary
        run: |
          cargo build --verbose
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        os: [production]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run tests
      run: cargo test --features=a2l_reader --features=serde -- --test-threads=1 --nocapture
    
